server:
  port: 8889
spring:
  #security:
  # user:
  #   name: admin
  #  password: a
  # roles:
  #  - USER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Asd8711341
    url: jdbc:mysql://101.200.216.156:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  application:
    name: microservice-provider
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长
logging:
  level:
    com.yc.springcloud1_2: debug
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      #defaultZone: http://localhost:7001/eureka
      #defaultZone: http://admin:a@localhost:7001/eureka  #授信用户登录
      defaultZone: http://admin:a@eureka1:7001/eureka,http://admin:a@eureka2:7002/eureka,http://admin:a@eureka3:7003/eureka
  instance:
    instance-id: microservice-provider-product_2   #实例名
    lease-expiration-duration-in-seconds: 90  #如果现在超过了5s的时间间隔( default: 90 s )
    lease-renewal-interval-in-seconds: 30   #设置心跳的时间间隔( default:30s )
#监控配置
info:
  app.name: MICROSERVICE-PROVIDER
  company.name: gsn
  build.artifactId: microservice-provider2
  build.modelVersion: 4.0.0
  build.version: 0.0.1-SNAPSHOT
  jdk.version: 1.8.0_65
